[package]
name = "magpie"
version = "0.5.2"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2018"
description = "Reasonably efficient Othello library built with bitboards"
repository = "https://github.com/LimeEng/magpie/"
license = "MIT"
keywords = ["othello", "reversi", "bitboard"]
categories = ["algorithms", "game-engines"]

exclude = [
    ".github/**"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
criterion = "0.3.3"
rand = "0.8.0"
unicode-segmentation = "1.7.1"
serde_json = "1.0.60"

[[example]]
name = "serde"
required-features = ["serde"]

[[test]]
name = "serde"
required-features = ["serde"]

[[bench]]
name = "othello_board"
harness = false

[profile.test]
opt-level = 3
