[package]
name = "magpie"
version = "0.2.0"
authors = ["Emil Englesson <englesson.emil@gmail.com>"]
edition = "2018"
description = "A simple Othello library built with bitboards"
repository = "https://github.com/LimeEng/magpie/"
license = "MIT"
keywords = ["othello"]

exclude = [
    ".github/**"
]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
criterion = "0.3.3"

[[bench]]
name = "othello_board"
harness = false

[profile.test]
opt-level = 3
